# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2b25312dff175496c75cee2f8dd5750fedfb96f4048202bdbfc7bb72739030014f9b83527feda908b87c75dafd7b8982e1cdeff92c751501221d743e387170cf

test:
  secret_key_base: fdb30e57c179fdba3d33202c536797b08f45863fec3c16c0e45ece1944acc945ee03168ece6708ad8f632066077cb95c93ed84e8785d194995994b6ce48ab7c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
